### ISSUE TITLE
The repository needs to be upgraded to framework version 3

### ISSUE THREAD

**Issue by drew-fierst** [drew-fierst/git-class#1]
Framework version 3 has been released and has some breaking changes. 

We need to upgrade our repository code to allow for use of version 3 of the framework.

**Comment by drewbaphone** [comment]
yeah, I experienced this same bug. please fix ASAP!

**Comment by drewbaphone** [comment]
any progress on this issue yet, @drew-fierst ??

**Comment by drew-fierst** [comment]
[https://github.com/drew-fierst/git-class/blob/main/blog/content.txt](the problem is in this file)

**Comment by drew-fierst** [comment]
``
